[package]
name = "ironyyy"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
easy_totp = "0.4"
rand_core = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["v4", "serde"] }
